### PR TITLE
Language Support for Statements and Answers

### PR DESCRIPTION
**Pull request by dankim444**
## Description
This PR introduces multilingual support for both statements and answers in the UI and backend. On the frontend, we can now render survey statements and answers in the appropriate UI language. On the server side, the backend has been updated to track the UI language in submitted answers and retrieve the correct language-specific columns for both statements and answers. When merged, this PR will close https://github.com/Watts-Lab/commonsense-platform/issues/146. 

## Changes
1. Translation files updated:
    - updates translation.json files for cypress tests and the UI
2. Language-based rendering on frontend
    - Components updated for multilingual support: Enter.tsx, Feedback.tsx, MutiStepForm.tsx, Question.tsx, Result.tsx, SocialSurvey.tsx, Statement.tsx, StatementForm.tsx, Layout.tsx, Dashboard.tsx, DashboardChart.tsx, NotificationBox.tsx, TwitterText.tsx
    - **Layout.tsx, Dashboard.tsx**: passes language as a parameter to API call, retrieves statements based on language, re-renders whenever language changes. 
3. Updated language selection of statements and answer in backend:
    - **/getanswers endpoint**: selects the correct statement column based on the UI language
    - **/ post answers endpoint**: tracks the UI language in answers submitted by the user
    - **treatment function**: queries the appropriate statements based on the UI language

## Notes
- I noticed some statements in the statements table haven't been normalized yet. However, if we are starting with a clean slate for the next experiment, this shouldn't be a problem.

### CODE REVIEW

**Comment by markwhiting** [comment]
What's the status on this? What is it waiting for?

**Comment by dankim444** [comment]
@markwhiting It's currently waiting for a review. @amirrr said he would be able to take a look at it, and then I can merge.

**Comment by markwhiting** [comment]
Thanks @dankim444 

@amirrr — can you take a look when you have a chance.

**Review by amirrr — APPROVED** [review]
Good job as always.

**Pull request merged**
